services:
  user-db:
    image: postgres:18-alpine
    container_name: user-postgres-db-local
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user-service
    volumes:
      - user-postgres-data-local:/var/lib/postgresql/data
    networks:
      - local-network

  rabbitmq:
    image: rabbitmq:4.1.4-management-alpine
    container_name: rabbitmq-local
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data-local:/var/lib/rabbitmq
    networks:
      - local-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data-local:/var/lib/pgadmin
    depends_on:
      - user-db
    networks:
      - local-network

volumes:
  user-postgres-data-local:
  rabbitmq-data-local:
  pgadmin-data-local:

networks:
  local-network:
    driver: bridge