services:
  user-db:
    image: postgres:18-alpine
    container_name: user-postgres-db-local
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - user-postgres-data-local:/var/lib/postgresql/data
    networks:
      - local-network

  customer-db:
    image: postgres:18-alpine
    container_name: customer-postgres-db-local
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_DB: customer-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - customer-postgres-data-local:/var/lib/postgresql/data
    networks:
      - local-network

  rabbitmq:
    image: rabbitmq:4.1.4-management-alpine
    container_name: rabbitmq-local
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data-local:/var/lib/rabbitmq
    networks:
      - local-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data-local:/var/lib/pgadmin
    depends_on:
      - user-db
    networks:
      - local-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-local.yml:/etc/prometheus/prometheus.yml
    networks:
      - local-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data-local:/var/lib/grafana
    networks:
      - local-network
    depends_on:
      - prometheus

volumes:
  user-postgres-data-local:
  customer-postgres-data-local:
  rabbitmq-data-local:
  pgadmin-data-local:
  grafana-data-local:

networks:
  local-network:
    driver: bridge