spring:
  application:
    name: customer-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev.proptech.com
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml
  rabbitmq:
    host: rabbitmq
    port: 5672

openapi:
  server:
    url: https://dev.proptech.com
  oauth2:
    authorization-url: https://dev.proptech.com/oauth2/authorize
    token-url: https://dev.proptech.com/oauth2/token

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true