spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8080
  rabbitmq:
    host: rabbitmq
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always

openapi:
  server:
    url: http://api-gateway:8080
  oauth2:
    authorization-url: http://auth-service:8080/oauth2/authorize
    token-url: http://auth-service:8080/oauth2/token