apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: "http://auth-service:8080"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_JPA_HIBERNATE_DDL-AUTO: "update"
