apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
type: Opaque
data:
  POSTGRES_DB: <BASE64_ENCODED_DB_USERNAME>
  POSTGRES_USER: <BASE64_ENCODED_DB_USERNAME>
  POSTGRES_PASSWORD: <BASE64_ENCODED_DB_PASSWORD>