services:
  user-service:
    build:
      context: ..
      dockerfile: user-service/Dockerfile
    container_name: user-service-dev
    ports:
      - "8081:8080"
      - "5005:5005"
    volumes:
      - ./target/classes:/app/classes
    environment:
      SPRING_PROFILES_ACTIVE: dev-docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/${USER_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${USER_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${USER_POSTGRES_PASSWORD}
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      - user-db

  user-db:
    image: postgres:18-alpine
    container_name: user-postgres-db-dev
    restart: always
    environment:
      POSTGRES_USER: ${USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_POSTGRES_DB}
    volumes:
      - user-postgres-data-dev:/var/lib/postgresql/data

volumes:
  user-postgres-data-dev:
    driver: local